= Database Leader Election (DbLeaderElection)
:toc:
:toc-placement!:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]




image:https://img.shields.io/badge/License-Apache%202.0-blue.svg[link="http://www.apache.org/licenses/LICENSE-2.0",target=_blank]
image:https://github.com/lbruun/dbleaderelection/actions/workflows/main.yml/badge.svg[CI,link="https://github.com/lbruun/dbleaderelection/actions/workflows/main.yml"]
image:https://maven-badges.herokuapp.com/maven-central/net.lbruun.springboot/preliquibase-spring-boot-starter/badge.svg[link="https://maven-badges.herokuapp.com/maven-central/net.lbruun.springboot/preliquibase-spring-boot-starter"]
image:https://javadoc.io/badge2/net.lbruun.springboot/preliquibase-spring-boot-autoconfigure/javadoc.svg[javadoc,link="https://javadoc.io/doc/net.lbruun.springboot/preliquibase-spring-boot-autoconfigure"]

*Database-driven leader election.*

Elect leader among distributed nodes using a common database as the mediator.

There are quite a few solutions available for leader election with different characteristics. 
However, they typically require separate infrastructure. If your application is already using 
a database for persistence then it would make sense to use that database also for leader election rather
than introducing another piece of architecture. This is where DbLeaderElect comes into the
picture. 


toc::[]


## Features

- No dependencies.
- No permanent JDBC session. This means it works transparently with a `DataSource` 
  from a JDBC Connection Pool implementation.
- Easy to reason about. Means we can express with great certainty the what it will be good at
  and what it will be less good at.
- Simple to use. Examples exists for use with Spring Boot or plain vanilla Java SE.
- Works with standard databases.
- Well tested. (we use TestContainers to simulate real-life)
- Supports fencing token when protection against dual leadership is important.
- Well documented.
- Easy on the database. The lease-based approach means that nodes only periodically need to 
contact the database.





== Why is leader election hard?

Leader election is difficult because any coordinated effort in a distributed environment is difficult.
Formally leader election is the process of reaching consencus among candidates. In a distributed
environment this is hard because there may be network partitions, unexpected delays and all sorts of other problems. 
In practice it is impossible to fully guarantee the outcome of such a process.


Before adding any form of leader election to your application you should evaluate carefully
what the given leader election mechanism 
The following is how DbLeaderElection tackles some of these challenges:

- *Central lock*. Creating a distributed locking mechanism that actually works as advertised is not for the
faint of heart. DbLeaderElection takes a well-proven approach by using the locking mechanism of a database to do the
hard work for us. Databases like PostgreSQL, MySQL and others have battle-tested functionality for 
exclusive row-level locking. This is what we use.

- *Lease-based*. DbLeaderElect uses a lease-based election mechanism. The holder of the lease is the leader.
However, the lease holder must periodically renew his lease to avoid other candidates from grabbing
the lease. If a lease hasn't been timely renewed then it is up for grabs. Eventually another
candidate will acquire the lease and thereby become leader. Unlike other leader election algorithms
the lease-based approach is easy to understand and easy to verify. 

- *Time concensus*. Agreeing on someting in a distributed environment often means that first the nodes
must agree on what time it is. Without clocks being syncronized it will often be impossible to safely
elect a leader, or even worse: the algorithm may apoint more than one leader concurrently. 
DbLeaderElect avoids clock synchronization issues by solely using the clock of the database. 
In fact we don't even care if the time on the database if incorrect, as long as it can 
correctly measure a _duaration_ using its clock. Using this approach the clock of the individual
nodes have no relevance. They simply don't play any role.



All in all DbLeaderElect provides guarantee that no two leaders will be _appointed_ at the same time.
The central mechanism will be consistent. However, we may still - at least theoretically - 
end up in the situation that there are two nodes which both _think_ they are the leader at the same time. Only one
of them actually is according to the database. The problem occurs when the process currently holding 
the lease (meaning is leader) for one reason or another is sleeping or is stalled such that it is not 
timely renewing its lease. Now another node is grabbing the lease and is now the new leader. But sudedenly 
the dormant process (the former leader) wakes up. It has in-memory knowledge that it is the leader so it 
will continue to do leader work. This will continue until it again approaches the database. Only then
will it come to know that in fact someone else is now leader. The problem can be mitigated by making more
frequent calls to the database. Perhaps the interval should be 10 seconds rather than 30 seconds? 
This will help, but only to some degree. To fully combat this situation, DbLeaderElect has another
feature: fencing token.

DbLeaderElect provides pretty good defence against there being multiple leaders, especially if you 
are able to take advantage of the fencing token. On the other hand - like any lease-based strategy - 
it isn't very good at ensuring that there is always a leader. You will have to accept that there
may be gaps where there is no leader at all. Even long gaps, up until the `assumeDeadMs` configuration
value. If this is 40 seconds then theoretically there can at worst case be no leader for 39.9 seconds 
depending on the time distribution for which candidates contact the database. (DbLeaderElection
tries to spread this a bit, so that even if candidates (nodes) are all started at the same time they will
not all contact the database at the exact same points in time).

Unlike other solutions which also use a database for central lock mechanism, DbLeaderElect does not
require each node to have a constant connection to the database. This makes DbLeaderElect 
easy on the database and adding many nodes is not per se a problem as long as your database can
handle many connections. Most databases are pretty good at this. In reality systems which need
leader election rarely have more than 10 nodes.

## Recommendations

If using leader election "for correctness", meaning that the tasks the leader is doing would
be catastrophic if was done twice, then use of a fencing token is highly recommended, if 
not mandatory. In most cases however, it would be better to ensure the tasks that the leader is doing are idempotent, 
meaning such tasks can be done twice without adverse effects. Then you would be using leader
election "for efficiency" and that is a much better situation to be in.


## Requirements




## Configuration







## Table



[source,sql]
----
CREATE TABLE db_leader_elect 
 (
     role_id               varchar(20)    NOT NULL,
     candidate_id          varchar(256)   NOT NULL,
     last_seen_timestamp   bigint         NOT NULL,
     lease_counter         bigint         NOT NULL,
 
     PRIMARY KEY (role_id)
  );
----

Table will never have more than a few rows so you need not be concerned about storage.

## Database support

Currently supported databases are:

- PostgreSQL (version 10 or later)
- MySQL (version 5.6 or later)
- Oracle (version 11 or later)
- Microsoft SQL Server (version 2016 or later)
- IBM Db2 for Linux, Unix and Windows (version 10.5 FP7 or later)
- H2 (only for testing, proof-of-concept, etc)




### Database support requirements

It will be possible to add support for most databases as the requirements that DbLeaderElection has
are really quite modest:

- Must support exclusive row-level locking, which means `SELECT .. FOR UPDATE` or something equivalent. 
  We use a simple brute-force test with 40 concurrent threads for a number of minutes to test if the database's implementation
  of this construct truly holds an exclusive row-level lock as we expect.
- Must support an expression which returns number of milliseconds since Unix epoch as a `BIGINT` type. 
  For example for PostgreSQL the expression is `CAST(EXTRACT(EPOCH FROM CURRENT_TIMESTAMP(3))*1000 AS BIGINT)`.
- Must support an atomic insert-if-not-exist statement. This is not part of ANSI SQL so will be
  proprietary to each database. For example PostgreSQL has `ON CONFLICT DO NOTHING` addition to INSERT statements,
  and MySQL has `INSERT IGNORE` statement. Note that constructs using `MERGE` or `NOT EXIST` are never
  safe to use under concurrent load. For databases which does not have out-of-the-box support it is
  acceptable to use a standard INSERT with try-catch and then ignore any duplicate key error (for example
  this is necessary for MS SQL Server)
- Must be supported by https://www.testcontainers.org/[Testcontainers project].


## Litterature

- https://martin.kleppmann.com/2016/02/08/how-to-do-distributed-locking.html["How to do distributed locking"]. 


- is already using a database. 
- can accept periods of no leader.
- is using the lead




- You want to setup database pre-requisites for Liquibase as part of your application code.
- You want to use the same database user for several environments (for the same application) but
you want each environment to use its own schema or own catalog. This is an inexpensive and simple
way of hosting multiple "editions" of your application on the same database server, for example your
'dev1, 'dev2', 'uat' and 'sit' environments can all use the same database user without clashing
with each other.
- Anything you can think of (but be sure not to use the module for something which Liquibase itself
  should rightfully do)



== Quick start (Maven)

. Add the following dependency to your project:

[source,xml]
----
<dependency>
    <groupId>net.lbruun.springboot</groupId>
    <artifactId>preliquibase-spring-boot-starter</artifactId>
    <version>  ---latest-version---  </version>
</dependency>
----
[start=2]
. Add SQL file(s) to folder `src/main/resources/preliquibase/` and name them `DBENGINECODE.sql` (where 'DBENGINECODE' is 
one of the string codes which are supported for database engine auto-detection, see <<auto_detection>>) or simply `default.sql` if 
the SQL file applies generically to any type of database engine. If your Pre-Liquibase script is about ensuring a 
schema exists (not unlikely, this is the main use-case for Pre-Liquibase) then your SQL script might look like this:

[source,text]
----
CREATE SCHEMA IF NOT EXISTS ${spring.liquibase.default-schema};
----

and application properties like this:

[source,properties]
----
spring.jpa.properties.hibernate.default_schema=${my.db.schemaname}
spring.liquibase.default-schema=${my.db.schemaname}
----

Now - in this example - the only thing left to decide is where the `my.db.schemaname` value
comes from. That is your choice. The link:examples/example1/[example project] advocates
that it should come from an OS environment variable, in particular if your are
deploying to a cloud.


Done!



== Usage 

The module is a Spring Boot V2 auto-configuration. Once you add the dependency to your application it will automatically
trigger its own auto-configuration if you also have Liquibase in your classpath. The module will make
sure it always fires _before_ Liquibase itself. The module has no effect if you add it to
a Spring Boot project which does not use Liquibase.

The module will search for SQL script files in pre-defined locations and execute those. You can have seperate SQL scripts 
for various database platforms (for example one for PostgreSQL and another for MS SQL Server, etc). At runtime the type of
database will be auto-detected so that the right SQL script is executed.

SQL script files can contain replacement variables on the form `${propertyName}` or `${propertyName:defaultValue}` so
as to make your SQL script file dynamic. The property will be resolved from your application's Spring Environment.

You can find an example project link:examples/example1/[here].


=== Maven dependency

The module's artifacts are available from Maven Central. True to how Spring Boot auto-configuration is organized you simply add a "Starter" 
to your project:

[source,xml]
----
<dependency>
    <groupId>net.lbruun.springboot</groupId>
    <artifactId>preliquibase-spring-boot-starter</artifactId>
    <version>  ---latest-version---  </version>
</dependency>
----

=== SQL Script syntax

The module uses the Spring Framework's build-in support for parsing and executing the SQL script file(s).

Rules for the file are:

- The syntax used must be native to your target database platform. You cannot use constructs from higher-level
  tools such as SQL*Plus (Oracle), `psql` (PostgreSQL) or `sqlcmd` (MS SQL Server).
- Statements ends with a semi-colon character. (by default, can be <<Configuration,customized>>)
- Comment lines start with `--`.
- Replacement variables on the form `${propertyName}` or `${propertyName:defaultValue}` can appear
  anywhere in the file so as to make your SQL script file dynamic. The property will be resolved from 
  your application's Spring Environment.
- The script should be idempotent code (only-create-if-not-already-exists statements), execute quickly 
  and generally be without side effects. Remember that the SQL script will be executed _every_ time 
  your application starts. Also, unlike Liquibase itself, Pre-Liquibase does not have a mechanism
  to ensure that the script only executes on only one node if your application is multi-node. To mitigate
  this the script should ideally be one atomic unit which the database engine can execute. Yet
  another reason why you would probably want to have only a single SQL statement in your script.
- Don't bother putting SELECT statements in the script. The result will not be shown anywhere.



=== How the module locates SQL script files [[sql_scripts_lookup]]

Pre-Liquibase locates the SQL script(s) to execute based on the value of the `sqlScriptReferences` 
configuration property. The default for this property is `classpath:/preliquibase/`.

In general, `sqlScriptReferences` is interpreted as a comma-separated list of 
https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#resources-resource-strings[Spring Resource textual
references]. It can be configured to either "folder mode" or "file mode":


1. Folder mode: Configure `sqlScriptReferences` to a single value ending in the "/" character.
In this mode the value will be interpreted as a folder location where SQL scripts to be executed
are found. From this folder, if a file named `preliquibase/DBPLATFORMCODE.sql` exists, it will be executed. 
`DBPLATFORMCODE` is a string code representing the type of database in use. The module will <<auto_detection,auto-detect>>
the database platform,  but you can optionally override the value with the `dbPlatformCode` configuration property. If no such file 
`preliquibase/DBPLATFORMCODE.sql` file exists the module will execute a file named `preliquibase/default.sql` if it exists.
If neither such file exists in the folder then no action will be taken (not an error).

2. File mode: Configure `sqlScriptReferences` to be a comma-separated list of individual SQL script files.
All of the SQL script files in the list will be executed, in the order they are listed.
Prior to execution of any SQL script file it is checked if all files mentioned actually exist, if not
a `PreLiquibaseException.SqlScriptRefError` is thrown.

NOTE: The way SQL script files are located and named is somewhat inspired by 
https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto-initialize-a-database-using-spring-jdbc[Spring Boot's DataSource Initialization feature]. 
However, there are some important differences: Pre-Liquibase auto-detects which database platform you are using and secondly if a platform 
specific SQL script file is found then Pre-Liquibase will not attempt to _also_ execute the platform generic file (`default.sql`).



=== Database platform auto-detection [[auto_detection]]

The module does not attempt to interpret the SQL you put in your SQL script files. It does, however, have a feature 
for auto-detecting which database platform is in use. It uses this information to figure out which SQL script file to
execute. This is ideal if your application is meant to support multiple database platforms.

Simply name your SQL script `preliquibase/DBPLATFORMCODE.sql` and put it in the classpath. For example, you may name your SQL script
file `preliquibase/postgresql.sql` and such script will then only be executed if the database platform in use is PostgreSQL.

Auto-detection is accomplished using Liquibase library, hence the DBPLATFORMCODEs you can use are the same as
can be used in an Liquibase `dbms` Precondition. For reference, here's a list of some of them:

* `postgresql`. PostgreSQL
* `mysql`. MySQL
* `mariadb`. MariaDB
* `mssql`. Microsoft SQL Server
* `h2`. H2 database
* `hsqldb`. HyperSQL database
* `oracle`. Oracle Database
* `db2`. IBM Db2 on Linux, Unix and Windows
* `db2z`. IBM Db2 on zOS
* `derby`. Apache Derby
* `sqlite`. SQLite
* `sybase`. Sybase Adaptive Server Enterprise
* `unsupported`. Database not supported by Liquibase




=== Configuration


WARNING: It is important that all instances (candidates) participating
in a leader election for a given role use exactly the same time configuration 
values (those values expressed as a duration: `intervalMs`, `assumeDeadMs`,
etc). If this is not the case then the leader election process will be
non-deterministic.

Reasonable defaults are defined for most properties.


[cols=3*,options=header]
|===
|Property name
|Type
|Description

|`assumeDeadMs`
|integer
|Defines the number of milliseconds after which the Leader Elector will decide that a leader is dead if it hasn't renewed its lease within this time. If a lease is older than this value, then the Leader Elector will assume the leader is dead - as leader candidate hasn't properly renewed its own lease - and the lease is now up for grabs by another candidate. Meaning another candidate may now assume leader role.

If set, the value must be at least 3 seconds larger than `intervalMs`. It is suggested to use a value 2x `intervalMs`. The difference between `assumeDeadMs` and `intervalMs` is the allowance for how late in renewing its lease a leader can be without risking being dethroned. The difference between the two must allow for network latencies, garbage collection stalls, temporary CPU starvation or any reason which will cause the renewal process to be late.

If not set: Defaults to 2x `intervalMs`, however at least 3 seconds.

|`roleId`
|String
|Role to compete for. Candidates compete for a particular role. Each role is an election of its own. 

The value must be no longer than 
https://javadoc.io/doc/net.lbruun.dbleaderelection/library/latest/net/lbruun/dbleaderelect/LeaderElectorConfiguration.html#ROLEID_MAX_LENGTH[ROLEID_MAX_LENGTH].
Most applications only need a single leader role to compete for and therefore do not need to set this value.

Defaults to 
https://javadoc.io/doc/net.lbruun.dbleaderelection/library/latest/net/lbruun/dbleaderelect/LeaderElectorConfiguration.html#DEFAULT_ROLEID[DEFAULT_ROLEID], 
if not set.

|`candidateId`
|String
|Defines an id for the current candidate. The value must be unique between all candidates participating
in a leader election for the same role.

The value must be no longer than 
https://javadoc.io/doc/net.lbruun.dbleaderelection/library/latest/net/lbruun/dbleaderelect/LeaderElectorConfiguration.html#CANDIDATEID_MAX_LENGTH[CANDIDATEID_MAX_LENGTH]
If longer, it will silently be truncated to this length.

Defaults to 
https://javadoc.io/doc/net.lbruun.dbleaderelection/library/latest/net/lbruun/dbleaderelect/utils/NodeIdUtils.html#getPidAndComputerName()[NodeIdUtils.getPidAndComputerName()]
if not set. For example: `32399@myhost`.
This will be sufficient for most use cases. Another possibility is to use an UUID value.

The NodeIdUtils class defines useful methods which can act as input to this value.

|`databaseEngine`
|https://javadoc.io/doc/net.lbruun.dbleaderelection/library/latest/net/lbruun/dbleaderelect//DatabaseEngine.html[Enum]
|Defines the type of database in use. The Leader Elector needs to know which type of database engine is in use as there are slight variations of the SQL grammar between database engines.

Defaults to `null` if not set. A value of `null` means the database type will be auto-detected at startup. 

|`schemaName`
|String
|Defines the name of the schema of the table which is used to keep track of current leadership. 
The schema must already exist.

Defaults to `null` if not set. The `null` value means to use the default schema of the database session.

WARNING: For MySQL/MariaDB the concept of "schema" is effectively synonymous with a database. Therefore, if this setting is used with MySQL/MariaDB it means in which _database_ the table is located.

|`tableName`
|String
|Unqualified name of the table which is used to keep track of current leadership. The table must already exist.

Defaults to 
https://javadoc.io/doc/net.lbruun.dbleaderelection/library/latest/net/lbruun/dbleaderelect/LeaderElectorConfiguration.html#DEFAULT_TABLENAME[DEFAULT_TABLENAME]
if not set.

|`intervalMs`
|integer
|Defines how often the lease is checked and/or renewed, in milliseconds. Every `intervalMs` a background thread in the Leader Elector will go to the database and either renew its current lease (if the candidate is currently the leader) or check if other leader has died and a new one should be promoted. The value is the interval between the checks (not including the check itself).

The lower this value is the smaller the amount of time which may pass without a leader.
If leadership gaps are generally undesirable then the value should be lowered. 
However, the lower the value the more strain on the database, especially with many candidates.

Defaults to 
https://javadoc.io/doc/net.lbruun.dbleaderelection/library/latest/net/lbruun/dbleaderelect/LeaderElectorConfiguration.html#DEFAULT_INTERVAL_MS[DEFAULT_INTERVAL_MS]
if not set.


|`createTable`
|boolean
|If the leader election table should be created if it does not already exist?. If `true``, then at every instantiation of LeaderElector class a check will be made to see if the table already exists. If not, it will be created.

The table will be created like this (generic form):

[source,sql]
----
 CREATE TABLE [<configuration.schemaName>.]<configuration.tableName>
  (
     role_id               VARCHAR(20)    NOT NULL,
     candidate_id          VARCHAR(256)   NOT NULL,
     last_seen_timestamp   BIGINT         NOT NULL,
     lease_counter         BIGINT         NOT NULL,
     PRIMARY KEY(role_id)
  )
----

(with column types replaced as appropriate for the given database engine)

|===

=== Examples

- link:examples/example1/[Example 1]. Using Pre-Liquibase with a single datasource.
- link:examples/example2/[Example 2]. Using Pre-Liquibase with multiple datasources. This requires configuring
  beans yourself, not just for Pre-Liquibase but also for Liquibase, JPA/Hibernate and so on. The
  example application shows how to do this. (in many ways it is a show-case application for how to
  to use multiple datasources in general in a Spring Boot application; the Pre-Liquibase part of it is trivial)


== Additional notes

=== Which DataSource is used?

The module will use the same DataSource as Spring Boot Liquibase module does. This seams
reasonable for an application with a single data source defined. However, it is possible to override this
by registering your own bean of type `PreLiquibaseDataSourceProvider` while still using auto-configuration
for everything else.

The other option is to configure the `PreLiquibase` bean(s) yourself in which case there's no need for
`PreLiquibaseDataSourceProvider`. Configuring `PreLiquibase` beans yourself will indeed be needed if the
application uses multiple data sources. Configuring the beans yourself allows unlimited flexibility.
However, it typically means you'll have to configure _all_ beans related to persistence
(Pre-Liquibase, Liquibase, JPA, JTA, etc) yourself as auto-configuration will back off.
An example of this can be found in link:example2/[Example 2].


=== To quote or not to quote?
You need to consider case (upper/lower) for the schema name. The SQL standard mandates that object names
are treated case-insentive if the value is not quoted.

However, there's a quirk in Liquibase. While Liquibase in general offers offers control over SQL object
quoting behavior (by way of the `objectQuotingStrategy` attribute in your changelog) the same is not true
in respect to Liquibase system tables, i.e. DATACHANGELOG and DATABASECHANGELOGLOCK. Here Liquibase will always
use the strategy named `LEGACY`. This means that SQL objects will be quoted if they are of mixed case, otherwise not.
This may create unexpected results with regards to the name of the schema holding the the Liquibase system tables.
Therefore, the advice is to *_use either all lower-case or all upper-case for schema name, never mixed case_*.
In short 'Foo_bar' is not a good value, but 'FOO_BAR' or 'foo_bar' is.

An example: 

Let's say you are asking Pre-Liquibase to execute a SQL script for PostgreSQL like this

[source,text]
----
CREATE SCHEMA IF NOT EXISTS ${my.db.schemaname};
----

and you are then telling Liquibase to use the exact same value:

[source,properties]
----
spring.liquibase.default-schema=${my.db.schemaname}
----

All is good?  No, not so, if the value for `${my.db.schemaname}` is of mixed case, let's say `Foo_bar`,
Liquibase will attempt to create its system tables in a schema named `"Foo_bar"` (quoted) but the Pre-Liquibase
SQL script will have created a schema in the database server with name `foo_bar` so you'll get an 
error on Liquibase execution. Hence the recommendation to not use mixed-case for the schema name. Such strategy
will work with any database platform.

=== Unit testing

You can use Spring Boot's `@DataJpaTest` annotation as you normally would because the Pre-Liquibase module 
registers itself as one of the auto-configs which are in-scope when this annotation is applied to a test class.

The link:examples/example1/[example project] showcases this.


=== Troubleshooting

Turn on logging. Depending on what you want to dig into here are some properties you may want to set:

[source,properties]
----
debug=true
logging.level.org.springframework.jdbc.datasource.init=DEBUG
logging.level.org.springframework.boot.autoconfigure=DEBUG
logging.level.net.lbruun.springboot.preliquibase=TRACE
logging.level.liquibase=TRACE
----

Pre-Liquibase assumes that you are using auto-configuration for Liquibase as well. If you are manually
configuring a bean of type `SpringLiquibase` then Pre-Liquibase will not fire. You can find the background
for this explained in https://github.com/lbruun/Pre-Liquibase/issues/5[Issue #5]. In such case you'll have
to configure all beans yourself. You can find an example of this in link:example2/[Example 2] which you can
easily adapt to a single datasource use-case.

== Spring Boot compatibility

Current version works with Spring Boot 2.6+ and has been tested with `2.6` and `2.7`. There's no reason why it
should not work with any future 2.x release of Spring Boot.



[cols=4*,options=header]
|===
|Pre-Liquibase version
|Spring Boot compatibility
|Git branch name
|Description

|1.2.x 
|Spring Boot 2.6 and later
|`master`
|Use this unless you absolutely *must* use an older version of Spring Boot.

|1.1.x
|Spring Boot 2.5
|
|No longer maintained

|1.0.x
|Spring Boot 2.3, Spring Boot 2.4
|`prior-to-spring-boot-2.5`
|No longer maintained.


|===




== Alternatives

You can in theory use Spring Boot's DataSource initialization feature or JPA DDL or Hibernate DDL as described 
https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization.using-basic-sql-scripts[here], 
but the Spring Boot guide clearly explains that you should not use such methods along side "a higher-level Database Migration Tool, 
like Flyway or Liquibase" because these methods are not guaranteed to execute before Liquibase and if they happen to do so 
at the moment they might not in the future. In constrast the Pre-Liquibase module is designed specifically 
for use with Liquibase and is guaranteed to _always_ execute before Liquibase itself.



== References

* Flyway, Liquibase competitor, has a feature for ensuring that the schema exists prior to executing the Flyway migration:  
  https://flywaydb.org/documentation/concepts/migrations.html#schema-creation[createSchemas option]. Liquibase has no equivalent feature.
* Executing some SQL prior to the Liquibase ChangeSets has been discussed several times on the Liquibase forum. Example threads:
  ** https://forum.liquibase.org/t/advice-on-how-to-create-a-schema-for-defaultschemaname/470[Advice on how to create a schema for defaultSchemaName]
  ** https://forum.liquibase.org/t/how-to-create-a-schema-for-defaultschemaname/4103[how to create a schema for defaultSchemaName]



